### PR TITLE
Restored AC-8363 - Add birth_year field to core profile

### PR DESCRIPTION
**Pull request by pbx**
## [AC-8363](https://masschallenge.atlassian.net/browse/AC-8363)

Recreated per [AC-8430](https://masschallenge.atlassian.net/browse/AC-8430).

_[Original PR](https://github.com/masschallenge/django-accelerator/pull/360)_

### CODE REVIEW

**Review by PrinceDavis — APPROVED** [review]
migration ran on accelerate ✅ 
code looks good ✅

**Comment by PrinceDavis** [comment]
@pbx do we need two reviewer on this to merge?

**Comment by pbx** [comment]
yes @PrinceDavis we want two on each PR.  @philophilo you available?

**Review by shanbady — APPROVED** [review]
looks good

**Review by philophilo — APPROVED** [review]
✅ app runs well
✅ migrations run as expected
✅ field is added

**Pull request merged**
