### PR TITLE
[AC-6976] Replace ProgramFamily location with Smart locations  

### PR DESCRIPTION
**Pull request by jonkiparsky**
https://masschallenge.atlassian.net/browse/AC-6976

Reviewing notes: 
- verify that the model changes here are correct and that the data migration does what we want. 
- verify that tests pass on AC-6976b (removing the deprecated fields from ProgramFamily) BUT DO NOT MERGE THAT PR UNTIL AC-6796 HAS BEEN DEPLOYED

This has a related PR on accelerate. Both PRs should merge simultaneously

### CODE REVIEW

**Comment by kitaka** [comment]
Taking code review

**Comment by mkiterian** [comment]
Taking QA

**Comment by mkiterian** [comment]
**QA**

- [ ] Tests are passing.
- [ ] Created a Program Family, a Location and associated the two
- [ ] Able to retrieve a program family's location

**Comment by mkiterian** [comment]
Looks good, awaiting changes on related PR

**Pull request merged**
