### PR TITLE
AC-8373 :: Delete old `gender` field 

### PR DESCRIPTION
**Pull request by freshprincekla**
**Changes introduced in [AC-8373](https://masschallenge.atlassian.net/browse/AC-8373)**
- removed old gender field for the base_core_profile and test contexts
- updated failing tests
- this PR is shipped with https://github.com/masschallenge/accelerate/pull/2938

**How to test**
- deployed to test4
- ensure that all views that had the old gender field are working
- this includes all reports
1 - mentor pool report
2 - mentorship report
3 - judging report 
4 - staff bucketlists
5 - allocation stats
This list is not extensive will add more as I find them.

### CODE REVIEW

**Comment by pbx** [comment]
(I'm holding off on this until after the failing tests on the other PR are fixed.)

**Review by pbx — APPROVED** [review]
Code changes look good, couldn't find anything that was overlooked.

**Review by jonkiparsky — COMMENTED** [review]
My only reservation about this is the possibility of blue/green issues. 

I believe that the safe procedure for deleting a field involves three distinct steps (each of which takes place on a different deploy)
- first, ensure that the field is optional and delete each place that accesses it (reads and writes)
- second, delete the field from the model
- finally, run the migration to delete the field from the table

@pbx  thoughts?

**Comment by pbx** [comment]
Labeling this PR "Don't merge" until we sort out the good question Jon raises.

**Comment by pbx** [comment]
@jonkiparsky I've removed the "Don't Merge" label from the sibling PR, because it's all about the first step in the three-step procedure you outlined. 

I'm looking over this PR's changes now but I think you're right that we should break them in two: one PR that removes the field and references to it, and a second PR that contains the migration which deletes the field from the DB.

**Review by jonkiparsky — APPROVED** [review]
I think this is safe to merge now that release 1.4.28 is underway

**Review by iankigen — APPROVED** [review]
Looks good
- the `gender` field and references to the gender field deleted ✅ 
- accelerate views continue working ✅

**Comment by iankigen** [comment]
LGTM

**Comment by freshprincekla** [comment]
@jonkiparsky and @iankigen, this PR is no longer blocked and might need another review to ensure that it doesn't mess up the Central Accounts epic.

**Pull request merged**
