### PR TITLE
[AC-9123] Remove Finalist tag from all staff accounts

### PR DESCRIPTION
**Pull request by AmosWels**
Changes introduced in [AC-9123](https://masschallenge.atlassian.net/browse/AC-9123)

Remove Finalist tag from all staff accounts

**How to test:**

- Check out this branch
- Run Migrations on your localhost
- Notice that no staff user has a finalist role grant

[you can find earlier reviews here](https://github.com/masschallenge/django-accelerator/pull/447)

### CODE REVIEW

**Review by iankigen — COMMENTED** [review]
- Receiving an exception when running the migration
```
raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
django.core.exceptions.FieldError: Related Field got invalid lookup: user_role
ERROR: 1
make: *** [migrate] Error 1
```
ref:
>List all finalist role grants and all staff clearances that user has as well as their active or inactive status

The shared [list](https://startupswin-my.sharepoint.com/:x:/g/personal/welike_masschallenge_org/ESS_MNO3xfRLgZpFhjygoOoBT9eC1dRmLNVAg0qglIcKGg?e=JgQD0I) does not contain staff clearances. Also, by role grants I suppose it means roles such as finalist, mentor e.t.c

**Comment by kenware** [comment]
Will it be difficult to include columns in the excel sheet that indicate the clearance name and role grants for each user as specified by the ticket?

**Comment by AmosWels** [comment]
> Will it be difficult to include columns in the excel sheet that indicate the clearance name and role grants for each user as specified by the ticket?

> yes it wouldn't be as direct, but since I already have the `staff_ids`, I've added another list with the staff clearance [here](https://startupswin-my.sharepoint.com/:x:/g/personal/welike_masschallenge_org/EY6mlosvbn9EnkJtyqZbOr4B2KZHxazy33CdGlx4jgPp_Q?e=cKWd93)

**Comment by AmosWels** [comment]
> * Receiving an exception when running the migration
> 
> ```
> raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
> django.core.exceptions.FieldError: Related Field got invalid lookup: user_role
> ERROR: 1
> make: *** [migrate] Error 1
> ```
> 
> ref:
> 
> > List all finalist role grants and all staff clearances that user has as well as their active or inactive status
> 
> The shared [list](https://startupswin-my.sharepoint.com/:x:/g/personal/welike_masschallenge_org/ESS_MNO3xfRLgZpFhjygoOoBT9eC1dRmLNVAg0qglIcKGg?e=JgQD0I) does not contain staff clearances. Also, by role grants I suppose it means roles such as finalist, mentor e.t.c

> I've updated the program role grants list to include both the program and the role grants for each staff user. You can find it [here](https://startupswin-my.sharepoint.com/:x:/g/personal/welike_masschallenge_org/Eap1fbYRzNJOr5xC_AoeDGQB1RvipjtDiegSsI2UL-a39Q?e=xwwIS0)

**Comment by hfreund** [comment]
@kenware & @AmosWels I'm concerned we're deviating from the purpose of this ticket. The first point of the done is very clear about the objective:
> Any user with a staff clearance does not have a Finalist role grant of any kind

There should be no changes made to any user who does not have a staff clearance.
In order to verify the correct changes will be made, this ticket requests an output file with the following data:
`|email |finalist_role_grant |active_status|`
It is not necessary to display a column indicating the staff clearance because list should only include users with a staff clearance. We don't care which clearance, only that they have some clearance that would indicate the account is that of a staff user.

**Review by iankigen — APPROVED** [review]
Code looks good
- Any user with a staff clearance does not have a Finalist role grant of any kind ✅

**Review by kenware — APPROVED** [review]
This looks good

**Pull request merged**
