### PR TITLE
[AC-9669]: assign legacy users to an HC based on  past confirmed roles

### PR DESCRIPTION
**Pull request by kenware**
[AC-9669](https://masschallenge.atlassian.net/browse/AC-9669)

How to test Using Django shell
- Fetch all program families of a user via the user program role grant
- pick the `home community` of a program family that has the smallest `assignment_order`
- Ensure it is the same home community set on that user profile.

### CODE REVIEW

**Review by shakirandagire — APPROVED** [review]
QA looks good.
✅ A migration exists which assigns users to Home Communities based on the logic above

**Comment by jonkiparsky** [comment]
Getting an error when I apply this migration:

```File "/django-accelerator/accelerator/migrations/0117_add_users_to_home_community_20220729_0641.py", line 15, in add_home_community_to_users
    users = User.objects.filter(**filter).distinct()
  File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/sql/query.py", line 1243, in build_filter
    raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
django.core.exceptions.FieldError: Related Field got invalid lookup: program```

**Comment by jonkiparsky** [comment]
@kenware Merged AC-9679, we'll need to update the migration number and dependency to reflect this.

**Comment by kenware** [comment]
> Getting an error when I apply this migration:
> 
> ```
>     users = User.objects.filter(**filter).distinct()
>   File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/manager.py", line 82, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/query.py", line 892, in filter
>     return self._filter_or_exclude(False, *args, **kwargs)
>   File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/query.py", line 910, in _filter_or_exclude
>     clone.query.add_q(Q(*args, **kwargs))
>   File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/sql/query.py", line 1290, in add_q
>     clause, _ = self._add_q(q_object, self.used_aliases)
>   File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/sql/query.py", line 1318, in _add_q
>     split_subq=split_subq, simple_col=simple_col,
>   File "/srv/www/mc/current/eggs/Django-2.2.24-py3.6.egg/django/db/models/sql/query.py", line 1243, in build_filter
>     raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
> django.core.exceptions.FieldError: Related Field got invalid lookup: program```
> ```

By any chance, your database corrupted? program field does exist in the `program role`

**Comment by jonkiparsky** [comment]
@kenware I've changed the target branch for this PR to be the Home Community epic branch AC-9645

Can you sanity-check this change for me?

**Comment by kenware** [comment]
> @kenware I've changed the target branch for this PR to be the Home Community epic branch AC-9645
> 
> Can you sanity-check this change for me?

Why we need to point it to develop is because of the ongoing work to merge Django-accelerator to accelerate. So it does not create confusion. This changes need to be merged before Django-accelerator is merged to accelerate

**Pull request closed without merging**
