### PR TITLE
Rename eventbrite_organization_id field to eventbrite_organizer_id

### PR DESCRIPTION
**Pull request by geofrocker**
#### Changes introduced in [AC-6749](https://masschallenge.atlassian.net/browse/AC-6749)
- Rename feild eventbrite_organization_id to eventbrite_organizer_id
#### How to test
- Checkout this branch and run `make migrate` in accelerate
- Follow [this link](http://localhost:8181/admin/mc/program/23/change/)
- Notice that the eventbrite_organization_id field has changed to eventbrite_organizer_id

### CODE REVIEW

**Comment by VincentHokie** [comment]
this is the type of PR that led to production issues a few weeks ago..

I propose you create a migration to create the new column only...and then later on we will create a migration to delete the old field. this will prevent errors from being thrown _while_ the deploy is happening on OpsWorks

**Comment by geofrocker** [comment]
I am going to do that.  We should have a follow up ticket for deletion though

**Comment by geofrocker** [comment]
Fixed @VincentHokie  cc @jonkiparsky

**Comment by jonkiparsky** [comment]
Reviewing code, need QA

**Comment by kaymation** [comment]
QA to compliment the other PR

**Pull request merged**
