### PR TITLE
[AC-6924] 'office_hour_is_in_past' utility function raises exception when 'start_date_time' is None

### PR DESCRIPTION
**Pull request by mkiterian**
### Changes introduced in [AC-6924](https://masschallenge.atlassian.net/browse/AC-6924):
- Make start_date_time and end_date_time fields non nullable

### How to test
- This change can't be tested directly

### CODE REVIEW

**Comment by kitaka** [comment]
Taking code review

**Comment by kitaka** [comment]
@mkiterian you should add a test

**Comment by mkiterian** [comment]
@kitaka we do not have an interface that would allow the creation of an office hour without a providing a start/end datetime. Testing this through model creation is like testing the django framework

**Comment by kitaka** [comment]
@mkiterian my thinking is that if an exception is being thrown on production, it should be reproducible with a test.

**Comment by kitaka** [comment]
@mkiterian as discussed on the call, the PR title was a bit misleading and its what inspired my request for a test. Given that this is a break away from the original ticket, it might have been better served as a micro ticket.

**Comment by geofrocker** [comment]
QA looks good. The following has been tested
- Migrations running successfully
- Office hour operations for finalist, mentor and staff

**Comment by EcoLek** [comment]
Is there a reason this hasn't been merged? Two approvals @kitaka @geofrocker

**Comment by geofrocker** [comment]
Not really

**Pull request merged**
