### PR TITLE
[AC-9373] Create revised /profile editing view: Community Info

### PR DESCRIPTION
**Pull request by iankigen**
## [AC-9373](https://masschallenge.atlassian.net/browse/AC-9373)

**Changes Introduced**
- add missing field: privacy_profile
- update geographic_experience field to allow multiple selections (M2M relationship)

**Testing**
- As a logged-in user, visit https://test-cam.masschallenge.org/profile/community  (Clear cache to get the latest style updates)
- Confirm that the definition of done according to [AC-9373](https://masschallenge.atlassian.net/browse/AC-9373) is satisfied

[Sibling PR](https://github.com/masschallenge/accelerate/pull/3188)

Feature flag: https://app.flagsmith.com/project/1247/environment/FWjYia93LozprcLiq5X4cQ/features

### CODE REVIEW

**Review by AmosWels — COMMENTED** [review]
changes look good to me, I've noticed that you removed the GeographicExperience field from coreprofile and created a model for it instead, was this the agreed position?

**Comment by iankigen** [comment]
@AmosWels according to the mockup, the geographic_experience is a multi-select(needs to be a m2m field). This should have been corrected in a bug ticket, however, I implemented it as part of AC-9373 mostly due to the time constraint

**Review by AmosWels — APPROVED** [review]
migrations run successfully and changes look good to me

**Review by kenware — APPROVED** [review]
Looks good

**Pull request merged**
